name: 'ls-lint'
description: 'An extremely fast file and directory name linter'
branding:
  color: blue
  icon: activity
inputs:
  config:
    description: 'ls-lint config file path(s)'
    required: false
    default: '.ls-lint.yml'
  workdir:
    description: 'change working directory before executing the given subcommand'
    required: false
    default: '.'
  error-output-format:
    description: 'use a specific error output format (text, json)'
    required: false
    default: 'text'
  warn:
    description: 'write lint errors to stdout instead of stderr (exit 0)'
    required: false
    default: 'false'
  debug:
    description: 'write debug informations to stdout'
    required: false
    default: 'false'
  paths:
    description: 'file or directory paths to lint'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'bin/index.js'